import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@chatscope/chat-ui-kit-styles/dist/default/styles.min.css';
import { styled } from '@mui/material/styles';
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { ThemeProvider } from "@mui/material/styles"; 
import {theme} from '@/app/theme';
import {Provider} from 'jotai';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
    <head>
      <title>Interview Simulation</title>
      <meta
        name="description"
        content="面接練習用アプリ"
      />
    </head>
    <body className="container mx-auto p-4">
        <Provider>
        <ThemeProvider theme={theme}>
        <Header title="InterviewSim"/>
        
              {children}
          
              <Footer/>
        </ThemeProvider>
        </Provider>
    </body>
  </html>
  );
}
