import type { Company } from "@/domain/company/entities";
import type { Resume } from "@/domain/resume/entities";
import type { InterviewSetting, ConversationLog, InterviewAnalysisResult } from "@/domain/interview/entities";
import type { InterviewHistory } from "@/domain/history_ranking/entities";
import type { User } from "@/domain/user/entities";

// Repository Interfaces (will be injected)
import type { IInterviewHistoryRepository } from "@/domain/history_ranking/repositories/IInterviewHistoryRepository";
import type { IInterviewAnalysisResultRepository } from "@/domain/interview/repositories/IInterviewAnalysisResultRepository";
import type { IConversationLogRepository } from "@/domain/interview/repositories/IConversationLogRepository";

export class HistoryService {
    private historyRepository: IInterviewHistoryRepository;
    private resultRepository: IInterviewAnalysisResultRepository;
    private conversationRepository: IConversationLogRepository;

    constructor(
        historyRepository: IInterviewHistoryRepository,
        resultRepository: IInterviewAnalysisResultRepository,
        conversationRepository: IConversationLogRepository
    ) {
        this.historyRepository = historyRepository;
        this.resultRepository = resultRepository;
        this.conversationRepository = conversationRepository;
    }

    public async recordInterviewHistory(
        user: User,
        totalScore: number,
        analysisResult: InterviewAnalysisResult,
        company: Company,
        resume: Resume,
        setting: InterviewSetting,
        conversationLog: ConversationLog,
        interestShift: number[]
        // uid: string, // Now part of User entity
    ): Promise<InterviewHistory> {
        try {
            // 1. Save individual components that might be separate aggregates or need their own IDs first
            //    The repositories should handle ID generation if not already present.
            //    The `userId` is passed for ownership/scoping if necessary at the repository level.
            const savedResult = await this.resultRepository.save(analysisResult, user.uid);
            const savedConversationLog = await this.conversationRepository.save(conversationLog, user.uid);

            // 2. Construct the InterviewHistory entity
            //    Snapshots are used as per the entity definition.
            //    IDs for company, resume, setting are assumed to be part of the input entities.
            const historyData: Omit<InterviewHistory, "id" | "conductedAt"> = { // ID and conductedAt generated by repo or later
                userId: user.uid,
                isRankIn: false, // Default, could be determined by another service/logic
                totalScore: totalScore,
                isRead: false, // Default
                companyId: company.id,
                resumeId: resume.id,
                settingId: setting.id,
                interestShift: interestShift,
                // Using snapshots
                interviewResultSnapshot: savedResult,
                companySnapshot: company,
                resumeSnapshot: resume,
                interviewSettingSnapshot: setting,
                conversationLogSnapshot: savedConversationLog,
            };

            // Add conductedAt before saving
            const completeHistoryData: InterviewHistory = {
                ...historyData,
                id: "", // Will be set by repository
                conductedAt: new Date(),
            } as InterviewHistory; // Cast because id is not yet set but repo expects it or handles it

            // 3. Save the main InterviewHistory entity
            const savedHistory = await this.historyRepository.save(completeHistoryData);

            console.log("Interview history recorded:", savedHistory);
            return savedHistory;

        } catch (e) {
            console.error("Error in HistoryService.recordInterviewHistory:", e);
            if (e instanceof Error) {
                throw new Error(`Failed to record interview history: ${e.message}`);
            }
            throw new Error("Failed to record interview history due to an unknown error.");
        }
    }
}

// Example Usage (for testing, would be in an application service)
/*
async function testHistoryService() {
    // Mock Repositories
    const mockHistoryRepo: IInterviewHistoryRepository = {
        save: async (history) => ({ ...history, id: "hist1", conductedAt: history.conductedAt || new Date() })
    };
    const mockResultRepo: IInterviewAnalysisResultRepository = {
        save: async (result, userId) => ({ ...result, id: "resOriginal1", uid: userId }) // Assuming uid was part of InterviewAnalysisResult for this mock
    };
    const mockConversationRepo: IConversationLogRepository = {
        save: async (log, userId) => ({ ...log, id: "convOriginal1", uid: userId }) // Assuming uid was part of ConversationLog for this mock
    };

    const historyService = new HistoryService(mockHistoryRepo, mockResultRepo, mockConversationRepo);

    // Mock data (replace with actual instances of domain objects)
    const mockUser: User = { uid: "user123", name: "Test User" };
    // Ensure mockAnalysisResult and mockConversationLog have 'id' and other fields as per their type definitions
    const mockAnalysisResult: InterviewAnalysisResult = { id: "ar1", isPass: true, isRead: false, positiveFeedback: {text:"Good"}, negativeFeedback:{text:"None"}, scores:{technical:10, communication: 8, learningDesire: 9, logicalThinking: 7, teamwork: 8, companyUnderstanding: 7} };
    const mockCompany: Company = { id: "comp1", uid: "u1", name: "TestCo", businessPosition: "", requiredSkillset: "", mission: "", productDetails: "", companyCulture: "", additionalInformation: "" };
    const mockResume: Resume = { id: "res1", uid: "u1", name: "John Doe", education: "", programmingExperience: "", qualifications: "", birthday: "", age: "", gender: 1, selfPromotion: "", researchAchievements: "", studentAchievements: "", reasonForApplication: "" };
    const mockSetting: InterviewSetting = { id: "set1", difficultyLevel: "普通", durationMinutes: 30, interviewType: "複合面接", interviewMode: "chat" };
    const mockConversationLog: ConversationLog = { id: "cl1", entries: [{role: "user", message: "Hello", timestamp: new Date()}] };
    const mockInterestShift = [3, 4, 5];

    try {
        const result = await historyService.recordInterviewHistory(
            mockUser, 60, mockAnalysisResult, mockCompany, mockResume, mockSetting, mockConversationLog, mockInterestShift
        );
        console.log("Recorded History:", result);
    } catch (error) {
        console.error("Test History Error:", error);
    }
}
// testHistoryService();
*/
