import { createClient, SupabaseClient } from "../../../../utils/supabase/client"; // Corrected relative path
import type { InterviewHistory } from "@/domain/history_ranking/entities";
import type { IInterviewHistoryRepository } from "@/domain/history_ranking/repositories/IInterviewHistoryRepository";
// Assuming a generic Supabase table helper class exists or we implement logic directly.
// For this example, we will write logic directly. A generic helper like `SupabaseDatabase` from `utils/supabase/database.ts` could be refactored into infrastructure.

export class SupabaseInterviewHistoryRepository implements IInterviewHistoryRepository {
    private supabase: SupabaseClient;

    constructor() {
        // If utils is outside src and @/ is src/*, this path needs adjustment.
        // Assuming for now that either utils is in src, or tsconfig paths handle it,
        // or it will be adjusted later. For now, using the provided path.
        this.supabase = createClient();
    }

    async save(history: InterviewHistory): Promise<InterviewHistory> {
        // Map InterviewHistory domain entity to the structure expected by the Supabase table "histories".
        // This might involve converting snapshots or complex objects into appropriate formats (e.g., JSON strings or foreign keys).
        // The original `addToHistory` saved `companyId`, `resumeId`, `settingId`, `conversationId`, `interviewResultId`.
        // Our `InterviewHistory` entity has snapshots. We need to decide how to store these.
        // Option 1: Store IDs of related aggregate roots if they are saved separately.
        // Option 2: Store JSON snapshots directly in the histories table.
        // For this implementation, let\'s assume we store IDs for related main entities,
        // and some core parts of snapshots if the table schema supports it.

        const historyTableData = {
            // id: history.id, // Supabase usually generates ID if not provided or if it is a primary key serial
            user_id: history.userId, // Ensure column names match DB (e.g., snake_case)
            is_rank_in: history.isRankIn,
            total_score: history.totalScore,
            is_read: history.isRead,
            company_id: history.companySnapshot.id, // Assuming companySnapshot has an id
            resume_id: history.resumeSnapshot.id,   // Assuming resumeSnapshot has an id
            setting_id: history.interviewSettingSnapshot.id, // Assuming settingSnapshot has an id
            conversation_log_id: history.conversationLogSnapshot.id, // Assuming it has an ID from its own table
            interview_result_id: history.interviewResultSnapshot.id, // Assuming it has an ID from its own table
            interest_shift: history.interestShift, // Supabase can store arrays
            conducted_at: history.conductedAt.toISOString(),
            // Storing entire snapshots as JSONB if the schema allows, otherwise select key fields.
            // For simplicity, we are primarily linking by ID here.
            // The domain entity holds the full snapshot for business logic,
            // but the DB might be more normalized.
        };

        const { data, error } = await this.supabase
            .from("histories") // Table name
            .insert(historyTableData)
            .select()
            .single(); // Assuming insert + select single returns the created record

        if (error) {
            console.error("Error saving interview history:", error);
            throw new Error(`Supabase error saving interview history: ${error.message}`);
        }

        if (!data) {
            throw new Error("Failed to save interview history, no data returned.");
        }

        // Map the returned data (DB row) back to an InterviewHistory domain entity if necessary.
        // Here, we assume the save operation was successful and the input `history` object
        // now has its ID if it was generated by the DB, or we return the `data` mapped to `InterviewHistory`.
        // For an insert, `data` should be the newly created record including its generated ID.
        return {
            ...history, // Spread the original to keep snapshots and other non-column properties
            id: data.id, // Use the ID from the database response
            userId: data.user_id,
            isRankIn: data.is_rank_in,
            totalScore: data.total_score,
            isRead: data.is_read,
            // We are not re-fetching snapshots here, assuming they are consistent.
            // The domain entity passed in already has them.
            // companyId, resumeId etc are on the entity via snapshots.
            interestShift: data.interest_shift,
            conductedAt: new Date(data.conducted_at),
        };
    }

    // Implement other methods like findById, findByUserId, etc. as needed.
    // async findById(id: string): Promise<InterviewHistory | null> {
    //     // ... implementation ...
    //     return null;
    // }
}
