name: Claude for Slack Issues

on:
  repository_dispatch:
    types: [claude-trigger]

jobs:
  claude-slack:
    if: github.event.client_payload.trigger_type == 'new_issue_with_claude_mention'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code for Slack Issue
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          custom_instructions: |
            - このIssueはSlackから自動作成されたものです
            - 実際のプロジェクトのコードを確認し、適切な対応を行ってください
            - 必要に応じてコードの修正やファイルの作成を行ってください
            - 完了後はプルリクエストを作成してください
          
          # オプション設定
          trigger_phrase: "@claude"
          label_trigger: "from-slack"
          branch_prefix: "claude/slack-issue-"
          use_sticky_comment: true