name: Test Slack Integration (Manual)

on:
  workflow_dispatch:  # 手動実行専用

jobs:
  test-slack-integration:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Slack API Connection
        run: |
          echo "Testing Slack API connection..."
          
          # 現在の時刻から1時間前のタイムスタンプを計算
          oldest=$(date -d '1 hour ago' +%s)
          
          # Slack APIでメッセージを取得
          curl -s -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
            "https://slack.com/api/conversations.history?channel=${{ secrets.SLACK_CHANNEL_ID }}&oldest=$oldest&limit=10" \
            > slack_response.json
          
          # レスポンスをチェック
          if [ "$(jq -r '.ok' slack_response.json)" = "true" ]; then
            echo "✅ Slack API connection successful"
            echo "Found $(jq '.messages | length' slack_response.json) messages"
            
            # 新しいメッセージをフィルタリング
            FILTERED_MESSAGES=$(jq -c '[.messages[] | select(.bot_id == null and (.reactions // [] | any(.name == "white_check_mark") | not))]' slack_response.json)
            
            if [ "$FILTERED_MESSAGES" != "[]" ] && [ "$FILTERED_MESSAGES" != "null" ]; then
              echo "✅ Found unprocessed messages"
              echo "Message count: $(echo "$FILTERED_MESSAGES" | jq 'length')"
              echo "First message: $(echo "$FILTERED_MESSAGES" | jq '.[0].text')"
            else
              echo "ℹ️ No new messages found"
            fi
          else
            echo "❌ Slack API Error: $(jq -r '.error' slack_response.json)"
            exit 1
          fi
          
          # Debug: Show response
          echo "Raw response:"
          cat slack_response.json | jq .